services:
  server:
    build: ./server
    environment:
      - NODE_ENV=production
      - WDS_SOCKET_PORT=5000
      - WATCHPACK_POLLING=true
    env_file:
      - ./server/.env
    ports:
      - 5000:5000
    volumes:
      - ./server/src:/app/src
  client:
    build: ./client
    environment:
      - WDS_SOCKET_PORT=4173
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    command: npm run dev
    depends_on: [server]
# Names our volume
volumes:
  my-db: