# GitHub Actions
# start on every pull-request

name: server-tests-workflow

on:
  pull_request

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      # - name: Goto server and run tests
      #   run: cd server && npm i && npm test